### ISSUE TITLE
the resultview dispaly frame is gray

### ISSUE THREAD

**Issue by justinshaohi** [saki4510t/OpenCVwithUVC#1]
hi @saki4510t 
in MainAcitivty ,the resultview display the frame from MyImageProcessorCallback is gray,how to be normal?thanks .

**Comment by saikrishna76** [comment]
Under opencv/jni/imageprocessor.cpp ,You can modify in dp_process for your favorite

**Comment by justinshaohi** [comment]
@saikrishna76 thanks,i have found where to change this.

**Comment by world9604** [comment]
Where do you need to change??

**Comment by world9604** [comment]
> @saikrishna76 thanks,i have found where to change this.

Where do you need to change??

**Comment by world9604** [comment]
I found the ImageProcessor :: do_process method.

**Comment by justinshaohi** [comment]
@world9604 change cv:cvtcolor to normal rgb
