### ISSUE TITLE
CpuMonitor, ViewAnimationHelper cannot resolve symbol

### ISSUE THREAD

**Issue by nickppbd** [saki4510t/OpenCVwithUVC#10]
Hi,
In MainActivity.java

```
import com.serenegiant.utils.CpuMonitor;
import com.serenegiant.utils.ViewAnimationHelper;

```
'cannot resolve symbol' problem happen.

What should I do?

**Comment by wahyuway** [comment]
You are missing common lib. Add this to your app build.gradle:

> implementation ('com.serenegiant:common:1.5.20') {
> 		exclude module: 'support-v4'
> 	}
then re-sync your project
