### ISSUE TITLE
ndk finished with non-zero exit value 2 [SOLVED] <- Let me save you some time :)

### ISSUE THREAD

**Issue by OuterObsessionSoftware** [saki4510t/OpenCVwithUVC#20]
After shifting through many issues trying to solve the "ndk finished with non-zero exit value 2" problem I finally found some answers. I thought I'd create this issue so in the future people can have a better idea who to solve the issue.

**~~The problem:~~** 
~~ndk finished with non-zero exit value 2~~

**The real problem:**
As most of us have figured the above error message basically means nothing, this is because when NDK is doing it's stuff any error messages don't get reported to Android Studio (at least by default) and instead we get a not so useful generic message.

**The solution:**
So really the solution is to obtain a meaningful error message, if we get a good error message we may be able to figure out what to fix.

Luckily there's a debug option if we use NDK from the command prompt, so we simply use:
`<ndk_build_path> -C <jni_path> NDK_OUT=<jniLibDir> all NDK_DEBUG=1`
Replace `<ndk_build_path>` `<jni_path>` `<jniLibDir>` with the corresponding paths for your case.

Now when we run the command NDK attempts to make the project but instead of successfully making the project we get an error and because we used the debug option we now get something meaningful!

Here's the error I got:

`*** Android NDK: APP_STL gnustl_shared is no longer supported. Please switch to either c++_static or c++_shared. See https://developer.android.com/ndk/guides/cpp-support.html for more information.    .  Stop.`

And from that we can instantly see the problem: `gnustl_shared` is no longer supported. This makes sense as in the new versions of NDK GCC is no longer supported.

To fix this I simply changed all of the instances of `gnustl_shared` to` c++_shared`.

This can be done through simply highlighting `gnustl_shared` right clicking and renaming via the refactor menu, alternatively you can press ctrl+shift+r and rename it that way.

Your error may be different but now that you can actually get a meaningful error message it shouldn't be anywhere as hard to solve :)

**Comment by OuterObsessionSoftware** [comment]
Solved :)

**Comment by matteotan** [comment]
Hi @OuterObsessionSoftware, how did you solve the "gnustl_shared is no longer supported"?

**Comment by OuterObsessionSoftware** [comment]
> Hi @OuterObsessionSoftware, how did you solve the "gnustl_shared is no longer supported"?

I explain how I fixed it in the original post.
The key part is:
"To fix this I simply changed all of the instances of gnustl_shared to c++_shared."
