### ISSUE TITLE
ndk-build.cmd'' finished with non-zero exit value 2

### ISSUE THREAD

**Issue by a-eye-tech** [saki4510t/OpenCVwithUVC#21]
Can someone please help me with this error?

org.gradle.process.internal.ExecException: Process 'command 'C:\Users\user\AppData\Local\Android\Sdk\ndk-bundle\/ndk-build.cmd'' finished with non-zero exit value 2

I have LLBD and CMake installed and updated on Android Studio 3.5.3.

**Comment by cp0418** [comment]
What is your NDK vesion? I have the same problem before I just downgrade to ndk 14 and it worked for me.

**Comment by a-eye-tech** [comment]
Oh, looks like I accidentally made an Issue post on the wrong git project. Sorry. But thanks for your reply @cp0418

**Comment by butterfly-coder** [comment]
I've got same error.
OS : Windows 10
Android Studio : 3.4
ndk : 20.0.5594570
error : Process 'command 'C:\Users\user\AppData\Local\Android\Sdk\ndk-bundle/ndk-build.cmd'' finished with non-zero exit value 2

**Comment by cp0418** [comment]
> I've got same error.
> OS : Windows 10
> Android Studio : 3.4
> ndk : 20.0.5594570
> error : Process 'command 'C:\Users\user\AppData\Local\Android\Sdk\ndk-bundle/ndk-build.cmd'' finished with non-zero exit value 2

Try to downgrade your ndk to version 14 download here >>https://developer.android.com/ndk/downloads/revision_history.html
Don't forget to set up your ndk location in your project structure.

**Comment by SkUnK-cc** [comment]
i solve it use ndk-r13b
