### ISSUE TITLE
Application has stopped after I click OK button to select camera.

### ISSUE THREAD

**Issue by cp0418** [saki4510t/OpenCVwithUVC#22]
![XA0US6NP](https://user-images.githubusercontent.com/52272847/71801957-06289180-308f-11ea-98d7-1afbb76d1a1b.jpg)

**Comment by SaadNaeemBhatti** [comment]
Same Issue

**Comment by Dev-Damon** [comment]
same,,, I've built with ndk ver 'r13b' Cos i have an error like " 'command 'C:\Users\ .... /ndk-build.cmd' ' finished with non-zero exit value 2"
and I connected 2 kinds of cameras, but it happened same.
Anybody solved this Prob???!  

HELP!!!!!  HELP!!!!!  HELP!!!!!

**Comment by EworkitSrl** [comment]
i get the same problem

**Comment by EworkitSrl** [comment]
did anyone solve it

**Comment by cp0418** [comment]
I can't solve it but i tried to use another library and it worked for me.
v
v
https://github.com/jiangdongguo/AndroidUSBCamera
