### ISSUE TITLE
opencv couldn't find "libgnustl_shared.so"

### ISSUE THREAD

**Issue by iAmYuhi** [saki4510t/OpenCVwithUVC#28]
Process: com.serenegiant.opencvwithuvc, PID: 1429 
   java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.serenegiant.opencvwithuvc-1/base.apk"],nativeLibraryDirectories=[/data/app/com.serenegiant.opencvwithuvc-1/lib/arm, /data/app/com.serenegiant.opencvwithuvc-1/base.apk!/lib/armeabi-v7a, /system/lib, /vendor/lib]]] couldn't find "libgnustl_shared.so"

**Comment by Manishinfo22** [comment]
How to solve opencv couldn't find "libgnustl_shared.so" this problem
